name: opml
description: A Dart package for parsing and building Outline Processor Markup Language (OPML) documents.
version: 0.3.0
homepage: https://github.com/daniel-keogh/opml

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  xml: ^5.4.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
