name: opml
description: A Dart package for parsing and building OPML documents.
version: 0.2.0
homepage: https://github.com/daniel-keogh/opml

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^5.1.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
