name: opml
description: A Dart package for parsing and building OPML documents.
version: 0.1.0
author: Daniel Keogh <dnlkgh@outlook.com>
homepage: https://github.com/daniel-keogh/opml

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  meta: ^1.2.2
  xml: ^3.6.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
