name: opml
description: A Dart package for parsing and building Outline Processor Markup Language (OPML) documents.
version: 0.4.0
homepage: https://github.com/daniel-keogh/opml

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  xml: ^6.2.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
